while 1:
    print("select a calc")
    print("1. F/A")
    print("2. A/F")
    print("3. P/A")
    print("4. A/P")
    print("5. F/P")
    print("6. P/F")
    x = input()

    if x == '1':
        print("i:")
        i = input()
        print("n:")
        n = input()
        print("A:")
        A = input()
        print(float(A)*((1+float(i))**float(n) - 1) / float(i))
    if x == '2':
        print("i:")
        i = input()
        print("n:")
        n = input()
        print("F:")
        F = input()
        print(float(F) * (float(i)) / ((1+float(i))**float(n) - 1))
    if x == '3':
        print("i:")
        i = input()
        print("n:")
        n = input()
        print("A:")
        A = input()
        print( float(A) * ((float(i)*(float(i)+1)**float(n))/((float(i)+1)**float(n) - 1))**(-1) )
    if x =='4':
        print("i:")
        i = input()
        print("n:")
        n = input()
        print("P:")
        P = input()
        print( float(P) * (float(i)*(float(i)+1)**float(n))/((float(i)+1)**float(n) - 1) )
    if x == '5':
        print("i:")
        i = input()
        print("n:")
        n = input()
        print("P:")
        P = input()
        print(float(P) * (1+float(i))**float(n))
    if x == '6':
        print("i:")
        i = input()
        print("n:")
        n = input()
        print("F:")
        F = input()
        print(float(F) * ((1+float(i))**float(n))**(-1))

